# Generated by Django 6.0.3 on 2026-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='media_file',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='update',
            name='media_file',
            field=models.FileField(blank=True, upload_to='updates/'),
        ),
        migrations.AddField(
            model_name='update',
            name='media_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
