# Generated by Django 6.0.3 on 2026-03-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_media_file_update_media_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='address',
        ),
    ]
