# Generated by Django 6.0.3 on 2026-03-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_request_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank'), ('mobile', 'Mobile Money')], max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='payment_target',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
