# Generated by Django 6.0.3 on 2026-03-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_request_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
